image: ruby:2.3

variables:
  JEKYLL_ENV: production

before_script:
  - bundle install


pages:
  stage: deploy
  script:
  - bundle exec jekyll build --config _config.yml,_config_gitlab.yml -d public
  artifacts:
    paths:
    - public
  only:
  - master

